package system.utils;

public enum RequestType {
    GET_BUILDINGS_LIST,
    MAKE_BOOKING,
    CONFIRM_BOOKING,
    CANCEL_BOOKING,
    INVALID_BOOKING_DETAILS,
    INVALID_CONFIRMATION_DETAILS,
    INVALID_CANCELLATION_DETAILS,
    BUILDINGS_LIST,
    BOOKING_MADE,
    BOOKING_CONFIRMED,
    BOOKING_CANCELLED
}
